### PR TITLE
Handle ValueError exceptions when doing a range request.

### PR DESCRIPTION
**Pull request by batlock666**
Fix in branch 1.5.x, so it can be used in Plone 4.3.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I fixed this with a direct commit on the branch: 3b00c720f71aaa91c16311015c05eb8d1a1c7720.

I thought the 4.3 pull request job used Python 2.6, but apparently I misremember. This would help to catch this beforehand. I use 2.6 locally in 4.3 core development to catch this in my own contributions.

**Comment by gforcada** [comment]
@mauritsvanrees thanks!

Regarding the 4.3 pull request job: no, it always has been using 2.7, but that's a very good point. I was rather thinking that at some point we should stop providing 2.6 support... especially when we start porting things to Python 3 😅

**Comment by jensens** [comment]
I think it's safe to stop providing 2.6 support even for Plone 4.3. ".. the Python 2.6 series is now officially retired. All official maintenance for Python 2.6, including security patches, has ended." https://www.python.org/download/releases/2.6.9/ (and this was as of 29. October 2013)

**Comment by mauritsvanrees** [comment]
For add-ons I usually only test on Travis with Python 2.7. But for core Plone 4.3, as long as it is still doable without too much effort, I would like to keep supporting 2.6. I hope everyone is on Python 2.7, but if it's just a few lines of code that need fixing to keep 2.6 support, then that is a good thing to do.

If 2.6 is causing us grieve and loss of sleep, we can drop it, I guess even in a point release. I have sometimes played with the idea of a Plone 4.4 release where we are a bit more adventurous (how is zc.buildout 2.x for an adventure...) and drop 2.6 support there. It's not going to happen.

Realistically, core Plone should still be fine for use with 2.6, but lots of add-ons can inadvertently have added 2.7-only code, so using 2.6 *is* getting more dangerous and unsupported  every day.

Fun additional note: this week, for a script, I used Python 2.3 on a Windows 2000 server. The Internet Explorer version there can't even access most https sites.  *whimper*

**Pull request merged**
