### PR TITLE
Add plone.namedfile storage utility for TemporaryFileWrapper.

### PR DESCRIPTION
**Pull request by frapell**

### CODE REVIEW

**Comment by frapell** [comment]
This is needed for https://github.com/plone/plone.app.contenttypes/pull/441

**Comment by jensens** [comment]
Is this still valid? If so, do you plan to push it further?

**Comment by frapell** [comment]
@jensens I don't know...  @enfold-josh?

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
