### PR TITLE
Revert "Fixing permission for download (refs #22)"

### PR DESCRIPTION
**Pull request by tisto**
Reverts plone/plone.app.blob#23

### CODE REVIEW

**Comment by tisto** [comment]
@vangheem merging this pull request most likely broke the 4.3 build: http://jenkins.plone.org/job/plone-4.3-python-2.7/401/changes#788e2f462ca53fd6be7e6140fdfccba52ef1bf49

**Comment by vangheem** [comment]
https://github.com/plone/plone.app.blob/pull/23 @david-batranu this broke the build.

**Comment by david-batranu** [comment]
Plone is broken without, test with 4.3.5 unified installer, try to download a file. Unless there's something i'm missing, the tests are bad.

**Comment by tisto** [comment]
Plone 4.3 uses p.a.blob 1.5.13:

https://github.com/plone/buildout.coredev/blob/4.3/versions.cfg#L131

Could be that a previous commit is responsible for those test failures. We should remove p.a.blob from auto-checkout to fix the build and then look into what is causing the failures.

**Comment by vangheem** [comment]
Right, we know. Just need to apply a fix without breaking build. I'll look
into it.

**Comment by vangheem** [comment]
Alright, fix is reapply and tests should be good now.

**Pull request merged**
